apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PBKPL-IT/MS-project.git
    targetRevision: HEAD
    path: deployment-service.yml
  destination:
    server: https://8BEE64BB9D434DE4E5927D1A32F33F84.gr7.us-east-1.eks.amazonaws.com
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
